title: babaniyi
author:
  name: Babaniyi Olaniyi
  email: horlaneyee@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
 Babaniyi is a Data Scientist in a health-tech firm based in Barcelona, Spain. 
 Currently, he focuses on applying machine learning to serve users at scale, from demand forecasting and experimentation models to building 
 reinforcement learning systems for mobile health recommendations.

show_excerpts: false # set to true to show excerpts on the homepage


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: by_niyi
    github:  Babaniyi
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: babaniyi
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/posts.md
  - _pages/projects.md
  - _pages/cv.md

include:
    - _pages

# Build settings
theme: minima

disqus:
  shortname: by_niyi

url: https://babaniyi.github.io


plugins:
 - jekyll-feed
 - jekyll-seo-tag


google_analytics: UA-NNNNNNNN-N

markdown: kramdown
mathjax: true